### ISSUE TITLE
Only works with classical UI

### ISSUE THREAD

**Issue by gelue** [kjempelodott/ananas#1]
Hi, 
Your program only works with the classical Fronter GUI, not Play.
When using Play GUI the Select room works fine, but the error '!! no tools available' is printed for all the rooms. When changing back to the classical designe everything works as it should. 

Love it by the way.

J

**Comment by kjempelodott** [comment]
Hi!

Oh, wow, I didn't know Fronter had more than one GUI :D Thanks for letting me know. I'll take a look at it

**Comment by kjempelodott** [comment]
Fixed! I couldn't find any other issues related to the Play GUI, so I'm closing this issue. Feel free to open a new one, in case I overlooked something
